author: "Chionesu George"
project:
  type: website
  render: 
    - index.qmd
    # - etl.qmd
    - question1.qmd
    # - question2.qmd
  output-dir: "../delriaan.github.io/content/data_projects/mcd_mdrp_database"
  execute-dir: "file"

website:
  title: "Exploring the MDRP Database"
  site-url: /
  navbar: 
    search: true
    left: 
      - text: "Home"
        href: index.html
      - text: "ETL"
        href: etl.html
      - text: "Question I"
        href: question1.html
      - text: "Question II"
        href: question2.html

format: 
  html:
    # self-contained: true
    code-overflow: wrap
    page-layout: full
    code-fold: true
    link-external-icon: true
    link-external-newwindow: true
    theme:
      light: flatly
      dark: slate

tags:
  - R
  - MDRP
  - Medicaid
  - Prescription
  - Drug