---
title: "Exploring the MDRP Database"
date: 2023-07-13
date-modified: last-modified
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: SETUP
#| echo: false
#| warning: false
#| message: false

knitr::opts_chunk$set(opts_chunk = list(cache=TRUE, cache.lazy=TRUE, warning=FALSE, message=FALSE))
source("setup.R");
```

```{=js}
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
# Introduction

This project explores the Medicaid Drug Rebate Program (MDRP) database.  Data is retrieved via the MDRP [API](https://data.medicaid.gov/dataset/0ad65fe5-3ad3-5d79-a3f9-7893ded7963a) (description [here](https://www.medicaid.gov/medicaid/prescription-drugs/medicaid-drug-rebate-program/medicaid-drug-rebate-program-data/index.html)) as well as general URL file retrieval routines:

```{r}
#| label: URLS
#| echo: false
urls$data
```

All files for this project are hosted on [GitHub](https://github.com/delriaan/port_MDRP_database)

<hr>

## Required LIbraries

```{r echo=FALSE}
tags$table(
  id = "req_libs_table"
  , tags$tr(
      tags$th(class="req_libs cran_libs", "CRAN", colspan = 3, width="67%; ")
      , tags$th(class="req_libs git_libs", "GitHub", width = "*")
      )
  , tags$tr(
      style = "align:top"
      , slider::slide(
          params$cran_libs
          , .after = 5
          , .step = 6
          , .f = \(x){ 
                map(x, \(i) tags$span(i, tags$br())) |> 
                tags$td(class="req_libs git_libs")
              }
          , .complete = TRUE
          ) |> 
          purrr::compact()
      , tags$td(class="req_libs cran_libs", urls$git_libs)
      )
  ) |> tags$p()
```


