---
title: "Question I: Correlation"
date: 2023-07-13
date-modified: last-modified
---

```{r}
#| label: SETUP
#| echo: false
#| warning: false
#| message: false

knitr::opts_chunk$set(opts_chunk = list(cache=TRUE, cache.lazy=TRUE, warning=FALSE, message=FALSE))
source("setup.R");

if ("global_drug_obs_smart_data" %in% .cache$keys()){
  cache_load(.cache, "drug_obs_smart_data");
  drug_obs_smart_data$cache_mgr(action = upd);
} else {
  stop("This section needs to be updated");
  
  drug_obs_smart_data <- smart.data$
    new(x = drug_obs_data, name = "drugs")$
    taxonomy.rule(!!!(drug_taxonomy %$% mget(ls())))$
    enforce.rules(for_usage)$
    cache_mgr(action = upd) |>
    invisible();
  
  cache_prep(drug_obs_smart_data) |> cache_save(.cache);
}

if ("global_drug_taxonomy" %in% .cache$keys()){
  cache_load(.cache, "drug_taxonomy");
} else {
  stop("This section needs to be updated");
  cache_prep(drug_taxonomy) |> cache_save(.cache);
}

```

At this stage, as this is an exploratory exercise, I sought to answer the question, "Is there a relationship between [`on_market_age`]{title="Days active on market"}, [`days_to_market`]{title="Days between FDA approval and going live on market"}, and [`route`]{title="Administration route"}:

```{r}
#| label: METRICS_CORRELATION
#| echo: false

# Define a base object
.tmp_obj <- get.smart("drugs")$
  use(identifier, metrics, retain = c(route), subset = days_to_market >= 0) |> 
  # View() 
  unique() |>
  modify_at("route", factor) |>
  setkey(route, alt_ndc, days_to_market, on_market_age);

# Create the first visualization focused on the correlation between days to market and on market age
drug_metric_oma_viz <- plot_metric_cor(data = .tmp_obj, metric = on_market_age, f = route);

# Create the second visualization focused on the correlation between days to market and days market absent
drug_metric_dma_viz <- plot_metric_cor(data = .tmp_obj, metric = days_market_absent, f = route);

# Create the third visualization focused on the correlation between days to market and days market absent
drug_metric_dma_oma_viz <- plot_metric_cor(data = .tmp_obj, metric = days_market_absent, primary_metric = on_market_age, f = route);

# Create the combined visualization
drug_metric_viz <- subplot(
  drug_metric_oma_viz
  , drug_metric_dma_viz
  , drug_metric_dma_oma_viz
  , nrows = 1
  , shareX = FALSE
  , shareY = TRUE
  , titleX = TRUE
  , titleY = TRUE
  );

# Send to cache
cache_prep(drug_metric_dma_viz) |> cache_save(.cache);
cache_prep(drug_metric_oma_viz) |> cache_save(.cache);
cache_prep(drug_metric_dma_oma_viz) |> cache_save(.cache);
cache_prep(drug_metric_viz) |> cache_save(.cache);

# Render the combined visualization
# .cache$get("global_drug_metric_viz") |> tagList();

(\(.obj){
  fml <- on_market_age ~ days_to_market*route;
  
  mdl <- lm(
    formula = fml
    , data = modify_at(.obj, c("on_market_age", "days_to_market"), as.numeric)
    );
  
  mdl.summary <- mdl |> summary() |> 
    broom::tidy() |> 
    filter(p.value <= 0.1) |>
    modify_at("p.value", \(i) round(i, 4));
  
  mdl.aov <- aov(mdl);
  
  rm(mdl); 
  
  mget(ls(sorted = FALSE));
})(.tmp_obj)
```
